In [51]:
import numpy as np
import pandas as pd

In [52]:
df = pd.read_csv("D:\\SBIN_Data\\SBIN_Data.csv")

In [53]:
df

            Date    Open    High     Low   Close  Volume      Time
0     01-01-2024  642.20  642.70  641.00  641.95   89481  09:15:00
1     01-01-2024  641.95  642.85  641.95  642.45   48965  09:16:00
2     01-01-2024  642.70  644.00  642.70  643.50   65729  09:17:00
3     01-01-2024  643.90  644.55  643.30  643.40   47909  09:18:00
4     01-01-2024  643.70  644.10  643.45  643.75   27645  09:19:00
...          ...     ...     ...     ...     ...     ...       ...
8245  31-01-2024  642.90  642.90  642.50  642.80  161605  15:25:00
8246  31-01-2024  642.90  642.95  642.50  642.90  143774  15:26:00
8247  31-01-2024  642.95  643.05  642.45  642.50  166278  15:27:00
8248  31-01-2024  642.50  642.65  641.40  641.70  138018  15:28:00
8249  31-01-2024  641.70  641.80  641.00  641.55   54342  15:29:00

[8250 rows x 7 columns]

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8250 entries, 0 to 8249
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    8250 non-null   object
 1   Open    8250 non-null   float64
 2   High    8250 non-null   float64
 3   Low     8250 non-null   float64
 4   Close   8250 non-null   float64
 5   Volume  8250 non-null   int64
 6   Time    8250 non-null   object
dtypes: float64(4), int64(1), object(2)
memory usage: 451.3+ KB

In [31]:
df.describe()

              Open         High          Low        Close         Volume
count  8250.000000  8250.000000  8250.000000  8250.000000    8250.000000
mean    630.800152   631.132764   630.458218   630.799848   44664.906061
std      10.210328    10.170256    10.254218    10.210798   49381.392621
min     601.400000   601.800000   600.650000   601.400000     821.000000
25%     623.900000   624.250000   623.500000   623.900000   16257.500000
50%     630.500000   630.900000   630.150000   630.500000   29342.000000
75%     639.950000   640.250000   639.650000   639.950000   54434.750000
max     651.750000   651.750000   650.950000   651.750000  856782.000000

In [32]:
df.isnull().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
Time      0
dtype: int64

In [58]:
# Step 1: Convert 'Date' and 'Time' columns to datetime format
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')
# df['Time'] = pd.to_datetime(df['Time'], format='%H:%M:%S').dt.time

In [59]:
df.sort_values(by=['Time', 'Date'], inplace=True)

In [62]:
df['Week'] = df['Date'].apply(lambda x: x.weekofyear)

In [67]:
df['Rank'] = df.groupby(['Time', 'Week'])['Volume'].rank(ascending = False)

In [69]:
df.head(60)

           Date    Open    High     Low   Close  Volume      Time  Week  Rank
0    2024-01-01  642.20  642.70  641.00  641.95   89481  09:15:00     1   5.0
375  2024-01-02  641.35  641.65  638.35  639.50  138514  09:15:00     1   4.0
750  2024-01-03  639.35  639.35  635.80  638.50  242023  09:15:00     1   1.0
1125 2024-01-04  642.50  643.90  641.00  643.60  172139  09:15:00     1   2.0
1500 2024-01-05  645.00  646.95  645.00  646.00  157580  09:15:00     1   3.0
1875 2024-01-08  640.00  641.15  638.45  639.95  165466  09:15:00     2   1.0
2250 2024-01-09  632.00  632.65  630.60  632.65  125618  09:15:00     2   4.0
2625 2024-01-10  624.80  624.80  622.10  624.75  135279  09:15:00     2   2.0
3000 2024-01-11  626.00  626.75  625.90  626.45  111305  09:15:00     2   5.0
3375 2024-01-12  623.80  623.80  621.60  622.45  125643  09:15:00     2   3.0
3750 2024-01-15  638.90  640.55  636.85  640.50  272536  09:15:00     3   2.0
4125 2024-01-16  640.00  640.90  639.20  640.30  106718  09:15:00     3   6.0
4500 2024-01-17  624.00  630.45  623.00  628.80  538643  09:15:00     3   1.0
4875 2024-01-18  625.20  629.40  622.35  628.55  269501  09:15:00     3   3.0
5250 2024-01-19  633.00  633.50  632.05  632.55  108564  09:15:00     3   5.0
5625 2024-01-20  629.00  632.70  629.00  632.25  116162  09:15:00     3   4.0
6000 2024-01-23  627.00  634.30  627.00  633.50  344848  09:15:00     4   1.0
6375 2024-01-24  609.95  610.25  606.10  609.85  195526  09:15:00     4   3.0
6750 2024-01-25  618.50  621.65  617.55  620.15  240744  09:15:00     4   2.0
7125 2024-01-29  619.00  619.00  615.60  617.90  265767  09:15:00     5   1.0
7500 2024-01-30  624.30  627.00  624.25  626.75  225294  09:15:00     5   2.0
7875 2024-01-31  626.40  626.40  623.25  624.35  121679  09:15:00     5   3.0
1    2024-01-01  641.95  642.85  641.95  642.45   48965  09:16:00     1   5.0
376  2024-01-02  639.60  640.25  639.35  640.00   52042  09:16:00     1   4.0
751  2024-01-03  638.50  638.85  638.05  638.15   83333  09:16:00     1   3.0
1126 2024-01-04  643.65  644.00  642.60  642.95   91723  09:16:00     1   2.0
1501 2024-01-05  646.00  646.05  645.50  646.00  113785  09:16:00     1   1.0
1876 2024-01-08  639.55  641.95  639.55  641.50   92058  09:16:00     2   3.0
2251 2024-01-09  632.50  633.85  632.50  633.55  103136  09:16:00     2   1.0
2626 2024-01-10  624.45  624.95  623.80  624.45   89032  09:16:00     2   4.0
3001 2024-01-11  626.10  626.95  626.10  626.50   92811  09:16:00     2   2.0
3376 2024-01-12  622.30  623.10  622.15  622.80   69886  09:16:00     2   5.0
3751 2024-01-15  640.00  640.75  639.55  640.35  169020  09:16:00     3   2.0
4126 2024-01-16  640.70  640.90  639.60  640.50  107706  09:16:00     3   3.0
4501 2024-01-17  628.35  631.10  627.15  630.40  609806  09:16:00     3   1.0
4876 2024-01-18  628.45  628.75  626.95  627.90   77874  09:16:00     3   5.0
5251 2024-01-19  632.65  633.00  631.75  632.35   67173  09:16:00     3   6.0
5626 2024-01-20  632.20  632.55  631.35  631.80   86289  09:16:00     3   4.0
6001 2024-01-23  633.50  634.00  632.65  633.65  116822  09:16:00     4   3.0
6376 2024-01-24  609.60  609.60  607.05  607.50  162590  09:16:00     4   2.0
6751 2024-01-25  620.40  621.35  618.10  619.20  243567  09:16:00     4   1.0
7126 2024-01-29  618.50  619.30  617.70  618.60  225794  09:16:00     5   1.0
7501 2024-01-30  627.00  627.50  626.30  627.20  147641  09:16:00     5   2.0
7876 2024-01-31  624.25  625.45  624.25  625.00   32389  09:16:00     5   3.0
2    2024-01-01  642.70  644.00  642.70  643.50   65729  09:17:00     1   3.0
377  2024-01-02  640.00  640.00  638.80  639.00   76197  09:17:00     1   2.0
752  2024-01-03  638.35  638.75  638.15  638.45   49513  09:17:00     1   5.0
1127 2024-01-04  642.75  643.35  642.50  643.00   50716  09:17:00     1   4.0
1502 2024-01-05  645.80  647.45  645.75  646.30  130700  09:17:00     1   1.0
1877 2024-01-08  641.50  642.45  641.25  641.85   48969  09:17:00     2   4.0
2252 2024-01-09  633.55  634.35  632.50  632.80  147368  09:17:00     2   1.0
2627 2024-01-10  624.45  624.50  623.75  624.30   56036  09:17:00     2   3.0
3002 2024-01-11  626.55  626.70  625.85  626.45   65026  09:17:00     2   2.0
3377 2024-01-12  622.90  623.00  622.50  622.95   47964  09:17:00     2   5.0
3752 2024-01-15  640.40  640.40  639.60  639.90  124343  09:17:00     3   4.0
4127 2024-01-16  640.50  642.35  640.50  642.15  280674  09:17:00     3   2.0
4502 2024-01-17  630.55  631.75  629.90  631.05  419003  09:17:00     3   1.0
4877 2024-01-18  628.20  629.75  627.95  628.50  144069  09:17:00     3   3.0
5252 2024-01-19  632.40  632.95  632.15  632.90   34752  09:17:00     3   5.0
5627 2024-01-20  631.80  631.95  630.90  631.00   29465  09:17:00     3   6.0